stages:
  - setup
  - clean
  - analyze
  - test

########
# Setup
########
setup:
  stage: setup
  tags:
    - apparence
    - macos
  script:
    - flutter channel stable
    - flutter upgrade
    - flutter pub get

########
# Cleans
########
clean:example:
  stage: clean
  tags:
    - apparence
    - macos
  script:
    - cd example/
    - flutter clean
clean:main:
  stage: clean
  tags:
    - apparence
    - macos
  script:
    - flutter clean

##########
# Analyzes
##########
#analyze:example:
  #stage: analyze
  #tags:
    #- apparence
    #- macos
  #script:
    #- cd example/
    #- flutter analyze
#analyze:main:
  #stage: analyze
  #tags:
    #- apparence
    #- macos
  #script:
    #- flutter analyze

#######
# Tests
#######
test:example:
  stage: test
  tags:
    - apparence
    - macos
  script:
    - cd example/
    - flutter test test
test:main:
  stage: test
  tags:
    - apparence
    - macos
  script:
    - flutter test test
