before_script:
  - cd example/
  - flutter clean
  - cd ../
  - flutter clean
  - flutter pub get

stages:
  - setup
  - test
  - build

########
# Setup
########
setup:
  stage: setup
  tags:
    - apparence
    - macos
  script:
    - flutter channel stable
    - flutter upgrade

########
# Analyzes
########
#analyze:example:
#  stage: analyze
#  tags:
#    - apparence
#    - macos
#  script:
#    - cd example/
#    - flutter analyze
#analyze:main:
#  stage: analyze
#  tags:
#    - apparence
#    - macos
#  script:
#    - flutter analyze

#######
# Tests
#######
test:example:
  stage: test
  tags:
    - apparence
    - macos
  script:
    - cd example/
    - flutter test --coverage test
    - bash <(curl -s https://codecov.io/bash) -t 7a600e86-7222-4af2-aad5-10b945a4442b
    - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
      - example/coverage/
test:main:
  stage: test
  tags:
    - apparence
    - macos
  script:
    - flutter test --coverage test
    - bash <(curl -s https://codecov.io/bash) -t 7a600e86-7222-4af2-aad5-10b945a4442b
    - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
      - coverage/

##########
# Builds
##########
build:example:android:
  stage: build
  tags:
    - apparence
    - macos
  script:
    - cd example/
    - flutter build apk --release -t lib/main.dart
  artifacts:
    paths:
      - example/build/app/outputs/flutter-apk/app-release.apk
