stages:
  - setup
  - clean
  - analyze
  - test
  - build

########
# Setup
########
setup:
  stage: setup
  tags:
    - apparence
    - macos
  script:
    - flutter channel stable
    - flutter upgrade
    - flutter pub get

########
# Cleans
########
clean:example:
  stage: clean
  tags:
    - apparence
    - macos
  script:
    - cd example/
    - flutter clean
clean:main:
  stage: clean
  tags:
    - apparence
    - macos
  script:
    - flutter clean

#######
# Tests
#######
test:example:
  stage: test
  tags:
    - apparence
    - macos
  script:
    - cd example/
    - flutter test test
test:main:
  stage: test
  tags:
    - apparence
    - macos
  script:
    - flutter test test

##########
# Builds
##########
build:example:android:
  stage: build
  tags:
    - apparence
    - macos
  script:
    - cd example/
    - flutter build apk --release -t lib/main.dart
