name: palplugin
description: A flutter plugin for your friend
version: 0.0.1
author: null
homepage: null

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  mvvm_builder: ^2.1.3+2
  http: ^0.12.2
  google_fonts: ^1.1.0
  package_info: ^0.4.3
  rxdart: ^0.24.1
  flutter_colorpicker: ^0.3.4
  dotted_border: ^1.0.6
  keyboard_visibility: ^0.5.6
  application_icon: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/palplugin/assets/images/logo.png

    - packages/palplugin/assets/images/create_helper.png

    - packages/palplugin/assets/images/create_helper/types/helper_type_fullscreen.png
    - packages/palplugin/assets/images/create_helper/types/helper_type_simple.png
    - packages/palplugin/assets/images/create_helper/types/helper_type_update.png

    - packages/palplugin/assets/images/create_helper/themes/black/helper_theme_black_fullscreen.png
    - packages/palplugin/assets/images/create_helper/themes/black/helper_theme_black_simple.png
    - packages/palplugin/assets/images/create_helper/themes/black/helper_theme_black_update.png


#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages

